version: '3.8'

services:
  gruasucabloggingms_keycloak:
    image: gruasucabloggingms_keycloak
    build:
      context: .
      dockerfile: GruasUcabLoggingMS_Keycloak/Dockerfile
    ports:
      - "5230:5230"
      - "7133:7133"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5230;https://+:7133
      - Keycloak__BaseUrl=https://keycloak-18gub-u30800.vm.elestio.app
      - Keycloak__Realm=Gruas_UCAB_1
      - Keycloak__ClientId=myclient
      - Keycloak__ClientSecret=RBoT8rZrC1TO0ZOAWwifDHdJmM5U5xbd
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
