version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    networks:
      - mynetwork

  gruasucabloggingms_keycloak:
    image: gruasucabloggingms_keycloak
    build:
      context: .
      dockerfile: GruasUcabLoggingMS_Keycloak/Dockerfile
    ports:
      - "5230:5230"
      - "7133:7133"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5230;https://+:7133
      - Keycloak__BaseUrl=http://keycloak:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
